### ISSUE TITLE
Navegador diferente

### ISSUE THREAD

**Issue by DanielHGomes** [dkeas/DManga#10]
Oi, gostei muito da tua ideia, bem legal. Parabéns!
Tive um problema quando tentei usar, algum erro de conexão.
Não sei se depende do navegador, eu vi que o firefoz é o mais usado, e já que eu uso o vivaldi talvez tenha dado algum erro em relação a isso.
Tens alguma ideia?
![Screenshot_86](https://user-images.githubusercontent.com/6059306/83175850-f4559280-a0f2-11ea-8399-00084d3158b4.png)

**Comment by davideas000** [comment]
Ola, parceiro. acho que é problema com versão do ruby, a que eu uso ainda é a 2.5. Eu vou atualizar aqui e ver se eu descubro qual é o problema. Outra coisa que pode ser é a tua conexão com a internet, mas se tu consegui acessar o mangahost no navegador, então. provavelmente, o problema é outro.

quanto ao navegador, não realmente importa.

**Comment by dkeas** [comment]
Ola, parceiro. acho que é problema com versão do ruby, a que eu uso ainda é a 2.5. Eu vou atualizar aqui e ver se eu descubro qual é o problema. Outra coisa que pode ser é a tua conexão com a internet, mas se tu consegui acessar o mangahost no navegador, então. provavelmente, o problema é outro.

quanto ao navegador, não realmente importa.

**Comment by DanielHGomes** [comment]
A versão do ruby que eu instalei foi a 2.7.1. Em relação a conexão com o mangá host, tudo normal. Acesso sem problema.

**Comment by dkeas** [comment]
eu atualizei pra funcionar com a versão 2.7. 
Atualiza: "gem update dmanga". Deve tá funcionando agora, pelo que eu testei aqui funcionou.
