### ISSUE TITLE
Dominio mangahost2.com Expirado Falha no Download

### ISSUE THREAD

**Issue by juveniljose** [dkeas/DManga#20]
Dominio mangahost2.com expirou, teria alguma maneira de alterar para o novo dominio que ele esta usando

**Comment by Miwer-a** [comment]
> Dominio mangahost2.com expirou, teria alguma maneira de alterar para o novo dominio que ele esta usando

https://github.com/dkeas/DManga/pull/16/commits/e33d1f832c7348f2f0752a85147e18c04f483b39

**Comment by dkeas** [comment]
eu atualizei o url. deve tá funcionando agora.

**Comment by juveniljose** [comment]
obg amigo
