### ISSUE TITLE
Não faz download de certos mangas

### ISSUE THREAD

**Issue by Keikunbr** [dkeas/DManga#4]
O dmanga não consegue fazer download de mangas cujo nome tenha caracteres que o Windows não suporta no nome da pasta. Exemplo:
dmanga -d "j:\mangas" "Saikin"
Iniciando busca em mangahost.net
Você quer baixar Saikin Kono Sekai wa Watashi dake no Mono ni Narimashita...... [s/n]?s
Quais capitulos você quer baixar? todos
ERRO: Diretorio epecificado não existe.
ERROR: No such file or directory @ dir_s_mkdir - j:\mangas/Saikin Kono Sekai wa Watashi dake no Mono ni Narimashita....../capitulo #1 - Saikin Kono Sekai wa Watashi dake no Mono ni Narimashita.......

O problema está no final da pasta que o script tenta criar. O Windows não suporta os pontinhos no final do nome da pasta e cria a pasta sem os mesmos, ai o script dá erro pois tenta gravar os arquivos na pasta com o nome que tem os pontinhos no final porém a pasta não existe.

**Comment by dkeas** [comment]
esse problema com os caracteres não suportados pelo Windos ja foi resolvido..
não lembro como funciona no windows mas acho que o name das particão tem que ser maiúsculo... tenta o comando assim:
dmanga -d "J:\mangas" "saikin"

mas caso tu tenha mudado o nome da partição (se é que isso é possivel) verifica que a pasta mangas existe na raiz da partição... e toma cuidado com as letras maiúsculas e minúsculas.. o nome da partição e da pasta tem que ser exatamente igual, contando as letras maiúsculas e minúsculas.
e caso nada resolva tenta baixar sem especificar a pasta assim ele vai baixar diretamente para a pasta Downloads.. para ver se funciona

**Comment by Keikunbr** [comment]
O erro é o mesmo pois o script tenta criar uma pasta onde no final do nome existe vários pontos e o Windows 10 não suporta isso e cria a pasta sem os pontos no final, daí quando o script tenta fazer o download dos arquivos ele não encontra a pasta com o nome que deviria ter sido criada e dá erro.
Faz o teste com o manga que citei e verá o erro.

**Comment by dkeas** [comment]
ah, entedi você ta falando do "......" no final do nome do manga, tem razão, acho que é um bug.
 ja tem uma função que verifica caracteres invalidos no nome de diretorio no Win, mas acho que esqueci do ponto :) .
fiz um patch.
atualiza o dmanga 'gem update' e para remover a versão anterior 'gem clean', acho que isso resolve o problema, mas não cheguei a testar no Win.

**Comment by Keikunbr** [comment]
Muito obrigado. Problema resolvido. Pelo que vi aqui você modificou o script para ele substituir os pontos no final do nome do manga por "_" e com isso o Windows cria o diretório correto agora.
Está funcionando perfeitamente.

**Comment by dkeas** [comment]
na verdade ele substitui qualquer caractere invalido por '_' em vez de apagar o caractere, isso por que em nome de manga como 'tokyo ghoul:re' ia ficar 'tokyo ghoulre' com tudo junto, o que fica ruim de ler.
blz qualquer problemas estamos ai.

**Comment by Keikunbr** [comment]
Caro colega, haveria a possibilidade de você fazer mais uma mudança no código do script? Da forma que está, ele está substituindo o ponto "." que existe no meio do nome do manga por um "_". Exemplo:
O manga Dr. Stone depois deste update quando baixo outro capítulo está sendo criada a pasta "Dr_Stone".
O script precisa eliminar o ponto somente quando ele estiver no final do nome do diretório a ser criado. Estando em qualquer outra parte do nome do diretório não tem problema.

**Comment by dkeas** [comment]
tem como fazer sim, mas eu tenho que saber exatamento onde o ponto é  problemas.

por exemplo:
- "nomeDoManga....", esse da problema.
- "nomeDoManga.algo", não é problema?
- "nome.Do.Manga", não é problema?
- "....nome do manga", esse é problema?

**Comment by Keikunbr** [comment]
O problema é somente quando tem pontos no final do nome do diretório. No início e no meio do nome o Windows aceita. Ou seja, é somente o primeiro exemplo que você citou.

**Comment by dkeas** [comment]
fiz um patch, agora os pontos são removidos somente do final ou inicio do nome.

:-)

**Comment by Keikunbr** [comment]
Testado e aprovado. Mais uma vez, um muito obrigado pela ajuda e pelo excelente projeto que você criou.

**Comment by dkeas** [comment]
blz

:-)
