### ISSUE TITLE
Não consigo fazer download de um manga

### ISSUE THREAD

**Issue by Keikunbr** [dkeas/DManga#5]
Não estou conseguindo usar o script para fazer o download do manga a seguir:
https://mangahost2.com/manga/is-mh21043

Se eu uso o comando dmanga -d "j:\mangas" "is", o script vai retornando uma lista gigantesca de mangas que tem o "is" no meio do nome e embora eu percorra a lista toda não aparece o manga I"s na lista para download.
Haveria possibilidade de ao invés de informar o nome do manga que se quer baixar e o script procurá-lo no servidor, informar diretamente a URL do manga como alternativa?
Tipo assim:
dmanga -d "j:\mangas "https://mangahost2.com/manga/is-mh21043"

**Comment by dkeas** [comment]
eu entendi qual é o problema. você não vai conseguir procurar por esse ai, o nome é muito generico e o problema ta no proprio site (tenta usar a caixa de buscas deles com esse nome).

a tua sugestão é muito boa, o negócio é tempo, isso não é tão simples quanto consertar um bug (vai ter que mover algumas partes do codigo, reescrever alguns metodos e escrever testes), mas acho que daqui a semana, no maximo um mês, quando eu tiver um dia livre eu implemento isso.

dica: se em alguma momento você achar que a lista retornada pelo dmanga ta muito grande ou o nome do manga é muito generico, tanta usar a caixa de busca do proprio site primeiro se ela não retornar o manga então o dmanga também não vai.

**Comment by Keikunbr** [comment]
O único jeito que vi de localizar o manga no campo e busca do manga host foi usando o nome em japonês "アイズ" (que aparece no campo Nome(s) Alternativo(s):), porém para isso eu teria que conseguir usar estes tipos de caracteres japoneses na busca do Dmanga.

**Comment by dkeas** [comment]
fiz um patch. 
contando que o teu terminal permita caracteres japonese, agora deve ser possivel pesquisar com esses caracteres, mas não testei no Windows, para atualizar 'gem update' e remover versão anterior 'gem clean'.

**Comment by Keikunbr** [comment]
Testei aqui é só funciona se eu usar o comando "chcp 65001" para mudar a codificação de página do console de comando do Windows 10. Ai eu uso o comando:
dmanga -d "j:\mangas" "アイズ", onde o nome em japonês do manga eu copio do site Mangahost. O console ao invés de exibir os caracteres em japonês mostra três quadrados porém o script Dmanga reconhece corretamente os caracteres em japonês e consegue localizar o manga permitindo o download.
Para o console exibir corretamente os caracteres em japonês, pelo que vi aqui, além de mudar a codificação de página via comando chcp, tenho que também mudar a fonte utilizada no console do padrão "Courier New" para a fonte "NSimSun".
Obrigado pela ajuda.

**Comment by dkeas** [comment]
ja que você mencionou os problemas que você teve, posso te dar algumas dicas.

primeiro o terminal do windows na verdade não foi feito nem para ser usado, a microsoft disponibiliza ele só de prache mesmo, existe opções melhores. minhas sugestões:
- http://cmder.net, é tipo o cmd mas funciona.
- https://www.msys2.org, esse também funciona
não posso afirmar com certeza mas eles provavelmente sabem lidar com caracteres japoneses.
outra opção é usar uma distro linux (essa é minha opção favorita) mas isso depende de para que que tu usa o sistema, se gosta de jogar todo tipo de jogo no computador, então não vai servir, se gosta de trocar arquivos do microsoft office com outras pessoas, então não vai servir também (existe uma alternativa ao office tão capaz quanto, o problema é que não é 100% compatível com o office).
recomendação de distros: 
- deepin, esse é o mais bonito
https://m.youtube.com/watch?v=U6cynq4K2PE

- elementary os, esse também é bonito
https://m.youtube.com/watch?v=4_d8zmB-7QE

- linux mint, esse é o mais rápido
https://m.youtube.com/watch?v=LmTZnT6PHiw

bom é isso, qualquer problem é só postar un issue.
