### ISSUE TITLE
Dmanga não funciona

### ISSUE THREAD

**Issue by XStein17** [dkeas/DManga#8]
Toda vez que eu tento usar acontece isso:

![Screenshot from 2020-01-28 14-00-41](https://user-images.githubusercontent.com/39869371/73286615-9eb9b980-41d6-11ea-8a10-4d60d3366209.png)

**Comment by dkeas** [comment]
tem razão, 
o problema era o link que não tava mais funcionado.
eu corrigi, deve ta funcionando agora.

blz?

**Comment by XStein17** [comment]
Obrigado, está funcionando agora.
